### ISSUE TITLE
no.hal.pg.osm.geoutil.LatLong.distance method inaccurate

### ISSUE THREAD

**Issue by Sti2nd** [hallvard/tdt4250-2017#1]
In our test for the Recycle Bottle Game we experienced that the distance method from no.hal.pg.osm.geoutil.LatLong returns wrong distance. See the code below where we create two points on the same location and distance should thus be 0.0.

```java
GeoLocation recycle_point = OsmFactory.eINSTANCE.createGeoLocation();
recycle_point.setLatitude(3.0f); recycle_point.setLongitude(3.0f);
		
GeoLocation point = OsmFactory.eINSTANCE.createGeoLocation();
point.setLatitude(3.0f); point.setLongitude(3.0f);
		
assertEquals(0.0, point.getLatLong().distance(recycle_point.getLatLong()));
```
Gives junit.framework.AssertionFailedError: expected:<0.0> but was:<0.0949307305463114>

**Comment by hallvard** [comment]
The algorithm is taken from http://www.geodatasource.com/developers/php
In general, there will be errors when using floating point calculations and trig. functions, although I'm surprised it happens in this case. Feel free to suggest improvements to the code.

You should always use the variant of assertEquals that takes an epsilon value giving the accuracy. Here the error is 10 cm. which is OK for a game like this.

**Comment by Sti2nd** [comment]
We used the delta value and allowed an error of 10 cm.
